### ISSUE TITLE
[백준] 11403 - 경로 찾기

### ISSUE THREAD

**Issue by soocy0718** [juyeonma/python-coding-test-study#298]
실버 1 
https://www.acmicpc.net/problem/11403

**Comment by soocy0718** [comment]
팀즈가 오류가 나서 여기서 출제된것만 찾아볼 수 있어서ㅜㅜ.. 일단 팀즈는 체크를 못하고 넣었는데 중복이라면 단톡방에 알려주세요! 다른 문제로 수정하겠습니다..!

**Comment by Yu-jiwon** [comment]
제가 사용하던 pc가 아니어서 다른곳에 문제를 풀었는데
제출 시간안에 깃허브로 정리 못할 것 같아서 일단 이렇게 제출할게요!ㅜㅜ
최대한 빨리 pr로 올리겠습니다
https://velog.io/@jiwon7689/%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8230914
